### PR TITLE
added profile for intrested technical writes

### PR DESCRIPTION
**Pull request by Dyrstiu**

### CODE REVIEW

**Comment by emckean** [comment]
Hi! Would you please make a new pull request adding your information in alphabetical order by surname/family name? If you only use one name, alphabetize under that name. If you have questions about where your name would go in order, please reply to this comment. (Please alphabetize by more than the first letter: for example, _Cat_ would go after _Call_ but before _Cave_.)

**Comment by Dyrstiu** [comment]
Hey @emckean if am correct I should add my information under other writers starting with Fel right?

**Comment by emckean** [comment]
So the names are LISTED firstname, surname, but they are alphabetized by surname. So if you have:

Anwar Able
Bill Lion
Caesar Sun

Someone named Amy Pleasant would go between Bill Lion and Caesar Sun.

**Comment by Dyrstiu** [comment]
Thanks alot ,got it

**Pull request closed without merging**
