### PR TITLE
Added information for Mayank Thakur

### PR DESCRIPTION
**Pull request by Person-Maink**

### CODE REVIEW

**Comment by Person-Maink** [comment]
@googlebot I signed it!

**Comment by Person-Maink** [comment]
@googlebot I fixed it.

**Comment by Person-Maink** [comment]
I don't know who else has authored this commit. I am the only author here, and I have only used one account to do so.

**Comment by Person-Maink** [comment]
@googlebot help

**Comment by emckean** [comment]
Hi! Would you please make a new pull request adding your information in alphabetical order by surname/family name? If you only use one name, alphabetize under that name. If you have questions about where your name would go in order, please reply to this comment. (Please alphabetize by more than the first letter: for example, _Cat_ would go after _Call_ but before _Cave_.)

**Pull request closed without merging**
