### PR TITLE
GSOD Application for hamza442-ali 

### PR DESCRIPTION
**Pull request by hamza442-ali**
I'm participating in GSOD, Please receive my pull request and merge it to through the Technical Writer documents.

### CODE REVIEW

**Comment by hamza442-ali** [comment]
@googlebot I signed it!

**Comment by hamza442-ali** [comment]
@googlebot I signed it!

**Comment by hamza442-ali** [comment]
@googlebot I signed it!

**Comment by emckean** [comment]
Closing this pull request as the 2021 program is over. The 2022 program will begin soon; you can add your information in the [2022 interested technical writers file](https://github.com/google/season-of-docs/blob/main/2022-participants/interested-technical-writers.md).

**Pull request closed without merging**
