### PR TITLE
Added about myself (Jaskirat Singh)

### PR DESCRIPTION
**Pull request by jaskiratsingh2000**
I have added about myself as a GSoD 2023 aspirant

### CODE REVIEW

**Comment by emckean** [comment]
Hi! It looks as if edits were made to other participants' information, would you please revert those edits and only add your own information (even if the other edits were just changes to whitespace)?
Thank you.

**Comment by jaskiratsingh2000** [comment]
Hi @emckean  Thanks for reviewing. I want to let you know that I made edits only to my own addition. Can you please check once again if possible?

Looking forward to hearing from you.

**Comment by emckean** [comment]
You can see the changes by looking at the diff: https://github.com/google/season-of-docs/pull/796/commits/d022465b257d224dede1500eb0ca30d9f4601a08

Your editor may have changed the line endings or changed spacing.

**Comment by jaskiratsingh2000** [comment]
Yeah, I can see that but I'm afraid that how did that happen. What can I do
to resolve this?

Thanks and Regards

**Comment by emckean** [comment]
Hi, unfortunately we can't give editor training. You can close this PR and start a new one and check your editor settings or try to use the web editor if it's available.

**Comment by jaskiratsingh2000** [comment]
@emckean I have made the another PR, can you please look into it?
Thanks

**Pull request closed without merging**
