### PR TITLE
Update Inteserested Participants with my name

### PR DESCRIPTION
**Pull request by St80ene**

### CODE REVIEW

**Comment by emckean** [comment]
Thanks for your interest in Season of Docs! I'm seeing a lot of changes in addition to your information, could you please revert those? (It may be that your editor is changing line breaks or similar.)

**Comment by St80ene** [comment]
Thanks for the feedback. Yes, it's from the editor. Please do you have any solution or suggestions on how to revert?

**Comment by emckean** [comment]
Unfortunately, we're not able to do tech support for pull requests.

**Comment by St80ene** [comment]
Done. Please review @emckean. Thanks.

**Comment by emckean** [comment]
Unfortunately I am still seeing many changes. I suggest that you close this PR and try a new one.

**Pull request closed without merging**
