### PR TITLE
Added Participant Information

### PR DESCRIPTION
**Pull request by rish-singhal**
Added my information in Participant document.

### CODE REVIEW

**Comment by rish-singhal** [comment]
@googlebot I signed it!

**Comment by emckean** [comment]
Hi! Would you please update your PR to add your information in alphabetical order by surname/family name?

**Comment by rish-singhal** [comment]
@emckean Done!

**Comment by emckean** [comment]
Closing this pull request as the 2021 program is over. The 2022 program will begin soon; you can add your information in the [2022 interested technical writers file](https://github.com/google/season-of-docs/blob/main/2022-participants/interested-technical-writers.md).

**Pull request closed without merging**
