### PR TITLE
Update interested-technical-writers.md

### PR DESCRIPTION
**Pull request by mandarvshinde**
Updated Mandar Shinde profile information

### CODE REVIEW

**Comment by emckean** [comment]
Hi! thanks for your interest in Season of Docs. Unfortunately you have a broken link that is making the page scroll, would you please fix? Thanks.

**Comment by mandarvshinde** [comment]
I have done the required changes. Please merge the branch and let me know if the content is breaking the file again.

**Comment by emckean** [comment]
Hi -- thanks for the update, you are almost there. :) Your "Skills" section should be in the third column. You can see how it looks right now at this link: https://github.com/google/season-of-docs/blob/5ebd8621a5721ef8458422aeb600c5abd86176b3/2023-participants/interested-technical-writers.md

**Comment by mandarvshinde** [comment]
@emckean Fixed it. Added more information. Please merge my content to the main branch.

**Comment by mandarvshinde** [comment]
@emckean I cannot see my name in the writers list. did I miss something or as the list is long it seems not visible. Please advise.

**Pull request merged**
