### PR TITLE
Submitting my application for GSOD 2024

### PR DESCRIPTION
**Pull request by LordCodex164**

### CODE REVIEW

**Comment by emckean** [comment]
Hi, please make sure your information is in the correct format (three columns only: Name | Links | Description). Thanks!

**Comment by LordCodex164** [comment]
> Hi, please make sure your information is in the correct format (three columns only: Name | Links | Description). Thanks!

@emckean pls kindly review the latest changes to the information description and approve, thanks

**Comment by emckean** [comment]
Looks like you still have too many columns -- you should have only two | in your entry. Thanks!

**Comment by LordCodex164** [comment]
> Looks like you still have too many columns -- you should have only two | in your entry. Thanks!

Done @emckean

**Comment by LordCodex164** [comment]
Thank you @emckean

**Pull request merged**
