### PR TITLE
Adding SrishtyM.md file to contributors list

### PR DESCRIPTION
**Pull request by Srish-ty**

### CODE REVIEW

**Comment by Srish-ty** [comment]
The cicd checks aren't passing, as radha_thakare.md is giving errors.

**Comment by Fung1117** [comment]
need to edit the interested-technical-writers.md

**Comment by Srish-ty** [comment]
> need to edit the interested-technical-writers.md

Thank you for bringing that to attention

**Comment by Srish-ty** [comment]
@emckean , please review

**Comment by emckean** [comment]
Hi! Please do NOT edit the interested-technical-writers file, that file is automatically generated. 

Your information should follow this format: Name | Links | Description -- only three columns, and only one line (no line breaks). 

Closing this PR; feel free to create a new one in the correct format. Thank you!

**Pull request closed without merging**
