### PR TITLE
Update interested-organizations.md

### PR DESCRIPTION
**Pull request by Dana-Acciavatti**
This is an update for support for iHRIS, CLA is in progress

### CODE REVIEW

**Comment by emckean** [comment]
Hi, we close PRs after two weeks if the CLA has not been signed. Please feel free to reopen if you sign the CLA.

**Comment by Dana-Acciavatti** [comment]
> Hi, we close PRs after two weeks if the CLA has not been signed. Please feel free to reopen if you sign the CLA.

Hi, the CLA was signed March 24

**Comment by Dana-Acciavatti** [comment]
> 

I requested a rescan following signature and requested a rescan just now. I have the document if that will help. thank you

**Comment by Dana-Acciavatti** [comment]
> Thank you! Did iHRIS sign as a corporation, and did you get added to the list of approved signers (as in the instructions here: https://github.com/google/season-of-docs/pull/995/checks?check_run_id=12086619522)?

ah, that may be the issue. We signed as IntraHealth International, which is the organization that develops iHRIS. Do we need to resubmit as iHRIS or does the IntraHealth one suffice?

**Comment by emckean** [comment]
I think the key thing is that your email address is associated with the org that signed, under whatever name -- if you can check on your end I'll do the same on mine.  :)

**Comment by Dana-Acciavatti** [comment]
> I think the key thing is that your email address is associated with the org that signed, under whatever name -- if you can check on your end I'll do the same on mine. :)

Thank you for your help with this!  The person who signed has an @intrahealth.org email address and is included in the CLA google group we set up.  I hope that helps, let me know if any other info is needed.

**Comment by emckean** [comment]
Thank you! I believe this issue is that the signer of this commit is not connected with the CLA -- the email addresses have to match.

**Comment by Dana-Acciavatti** [comment]
> Thank you! I believe this issue is that the signer of this commit is not connected with the CLA -- the email addresses have to match.

My email address, which is associated with this commit, is also included in the CLA google group. I'm not sure why it wouldn't be associated....

**Comment by emckean** [comment]
Let me dig deeper on my end, might not be until end of day PT, I'm afraid! I apologize for the hassle.

**Comment by emckean** [comment]
Okay, I think the issue is that this commit is signed with a GitHub email address, and not your corporate email address? You can see in the failed check that the email address that is failing is an `@users.noreply.github.com` address.

**Pull request closed without merging**
