### PR TITLE
Add Mukhtar Abdulfatai to GSOD 2024

### PR DESCRIPTION
**Pull request by DevMukhtarr**

### CODE REVIEW

**Comment by DevMukhtarr** [comment]
@emckean kindly check this

**Comment by emckean** [comment]
Hi, unfortunately we cannot merge until you've signed the CLA. Thank you!

**Comment by DevMukhtarr** [comment]
Hello @emckean i have signed the CLA just now, can you check it again

**Comment by emckean** [comment]
Hi, do not add your name to input.txt, that is created automatically. I'm closing this PR, please open a new one following the instructions.

**Pull request closed without merging**
