### PR TITLE
Add Ayomide to interested technical writers for 2024 GSOD

### PR DESCRIPTION
**Pull request by AyomiCoder**

### CODE REVIEW

**Comment by emckean** [comment]
Hi! Please remove the ` ` from your entry, they're not needed. Thank you!

**Comment by emckean** [comment]
closing this as it's been a week with no response. feel free to reopen if you have an update!

**Comment by AyomiCoder** [comment]
Hello, i'm not sure what you asked me to remove from my entry. Please check your previous comment.

**Comment by emckean** [comment]
Please remove the quote marks at the beginning and end of your information, thank you.

**Comment by AyomiCoder** [comment]
I already made another PR and it has been added. Thank you.

**Pull request closed without merging**
