### PR TITLE
Added interested writer details

### PR DESCRIPTION
**Pull request by kwennB**

### CODE REVIEW

**Comment by emckean** [comment]
Hi! Please do not edit any files other than your own data file (YOURNAME.md). The other files are automatically generated.

**Comment by kwennB** [comment]
> Hi! Please do not edit any files other than your own data file (YOURNAME.md). The other files are automatically generated.

Yes @emckean sorry about that.

**Comment by emckean** [comment]
Hi, I'm not seeing any updates; did you push your commits to your branch?

**Comment by kwennB** [comment]
> Hi, I'm not seeing any updates; did you push your commits to your branch?

https://github.com/google/season-of-docs/pull/1269/commits/db3df430067844e4f3cbc90ab7a2c4b47ded6676

yes I did.

**Comment by emckean** [comment]
Please revert the changes to the interested-technical-writers.md, input.txt, and clean-input.txt files. Thank you!

**Pull request closed without merging**
