### PR TITLE
Adding my details for GSOD

### PR DESCRIPTION
**Pull request by Tes-program**

### CODE REVIEW

**Comment by Tes-program** [comment]
Hi @emckean,
I opened a new PR as you suggested and I am still having the same issues. Is there anything I can do, please? My primary email is the same as the one used to sign the CLA and push the commit to git. I am looking forward to your response.

**Comment by emckean** [comment]
Can you tell me what you have searched for to solve this problem so that I don't duplicate any effort? 

In the failed check it is looking like the PR opener and the commit author are showing up as different accounts.

**Comment by Tes-program** [comment]
Sure I have cross-checked my primary email and ensured that my **email address is not private**  as shown in the image below
Screenshot from 2023-03-09 18-53-00
I also ensured that my details correspond with the details i filled in the CLA.
Though i inputted my name as Tes-program but anytime i check the details it appears as a small letter. I don't know if that's the reason i can't sign the CLA
Screenshot from 2023-03-09 18-56-20

Also ensured my commit email matches the one in the CLA
image

Thank you for taking the time to respond to me. Thank you very much.

**Comment by emckean** [comment]
Can you check your git config user.name? I think it should be `tes-program` (the capitalization shouldn't matter).

**Comment by emckean** [comment]
Hi, I think I tracked it down, the email address in your git config does NOT match your CLA email. It is missing a 'u'. If you update that and then update your commit to use the correct email address that should work!

**Comment by Tes-program** [comment]
I will do that. Thank youuuu

**Pull request closed without merging**
