### PR TITLE
Update interested-technical-writers.md

### PR DESCRIPTION
**Pull request by joelbyronbarker**
Add Lion's Way.

### CODE REVIEW

**Comment by joelbyronbarker** [comment]
@googlebot I signed it!

**Comment by CynthiaPeter** [comment]
@googlebot I signed it!

**Comment by joelbyronbarker** [comment]
@googlebot I signed it!

**Comment by joelbyronbarker** [comment]
Hey @CynthiaPeter I am not clear how you got onto this pull request, but since there is a bot that needs to confirm who is on the contributor license agreement (CLA) it is holding up our ability to get it accepted! I think that what you need to do is to make your own fork from the main (just editing the original will start that process). I am pretty determined to get this done tonight so I am looking into just closing this PR and opening a new one.

**Pull request closed without merging**
