### PR TITLE
Add Matthias Baetens to technical writers

### PR DESCRIPTION
**Pull request by matthiasa4**

### CODE REVIEW

**Comment by phanendharreddy** [comment]
Goto CLA google page and sign in (by giving your email and  GitHub username) over there
that will help you with no further conflicts will be araised again

**Comment by matthiasa4** [comment]
> Goto CLA google page and sign in (by giving your email and GitHub username) over there that will help you with no further conflicts will be araised

Thanks! All done now :)

**Comment by emckean** [comment]
Hi Mattias, you may need to click the [link](https://cla.developers.google.com/github/rescan?pr=google%2Fseason-of-docs%2Fpull%2F647&key=%01x%1C%26bK%5EP%FB~%5D5i2%ABm%E4%83%AF%A5%9E&expiry=2023-03-05) in the failed check for the CLA to be updated

**Comment by matthiasa4** [comment]
Thanks @emckean ! Looks like we're good to go now :)

**Pull request merged**
