### PR TITLE
Added Srishty M to interested technical writers 

### PR DESCRIPTION
**Pull request by Srish-ty**
In this PR:
- created srishtym.md file
- wrote about me and my experience of technical writing in markdown file

### CODE REVIEW

**Comment by emckean** [comment]
Hi! Please follow our template -- your information should be only one line, and in this format: Name | Links | Description

**Comment by Srish-ty** [comment]
> Hi! Please follow our template -- your information should be only one line, and in this format: Name | Links | Description

Okay. Made changes https://github.com/google/season-of-docs/pull/1433/commits/1e1d573841e5b985425078fd73d340c7314fcafc

**Comment by Srish-ty** [comment]
@emckean , is the format correct now? Please review

**Comment by Srish-ty** [comment]
@emckean , please review

**Comment by emckean** [comment]
Hi, unfortunately your information is still showing up as multiline. Please update to match the format. Thank you!

**Comment by Srish-ty** [comment]
> Hi, unfortunately your information is still showing up as multiline. Please update to match the format. Thank you!

Okay thanks for letting know. I've made those changes.

**Comment by Srish-ty** [comment]
@emckean , please review and merge the pr.

**Comment by Srish-ty** [comment]
@emckean , please review and merge the pr

**Comment by emckean** [comment]
Hi, I'm afraid your file is still not correct. Please follow our template and include only three columns: Name | Links | Description (there should be only two | in your file). Thank you!

**Comment by Srish-ty** [comment]
> Hi, I'm afraid your file is still not correct. Please follow our template and include only three columns: Name | Links | Description (there should be only two | in your file). Thank you!

@emckean  Thank you for informing. I've ade necessary changes.
Commit - https://github.com/google/season-of-docs/pull/1433/commits/8f3ffd7ad63deeea430260f945abf09061a58664 . Please review

**Comment by Srish-ty** [comment]
@emckean, please review

**Pull request merged**
