### PR TITLE
Added Licio Lentimo to interested technical writers list

### PR DESCRIPTION
**Pull request by liciolentimo**

### CODE REVIEW

**Comment by liciolentimo** [comment]
@googlebot I signed it!

**Comment by emckean** [comment]
Hi! Would you please make a new pull request adding your information in alphabetical order by surname/family name? If you only use one name, alphabetize under that name. If you have questions about where your name would go in order, please reply to this comment. (Please alphabetize by more than the first letter: for example, _Cat_ would go after _Call_ but before _Cave_.)

**Comment by liciolentimo** [comment]
Revert to this pull request https://github.com/google/season-of-docs/pull/214

**Comment by emckean** [comment]
Hi, closing this, left comment on your other PR, please take a look and make another PR, thank you!

**Pull request closed without merging**
