### PR TITLE
Add CloudCV organization and link to proposal

### PR DESCRIPTION
**Pull request by RishabhJain2018**
This PR --
- [x] Add CloudCV as an interested participating organization in Google Season of Docs 2021.

### CODE REVIEW

**Comment by RishabhJain2018** [comment]
@googlebot I signed it!

**Comment by RishabhJain2018** [comment]
@emckean Please review and merge this PR.

**Comment by emckean** [comment]
hi, b/c of the merge conflict, I added your org manually. Please check the file to be sure it is correct. Thank you!

**Comment by RishabhJain2018** [comment]
Hi @emckean, Thank you for helping me with it. I checked it and it looks good to me.

**Pull request closed without merging**
