### PR TITLE
Updated the file

### PR DESCRIPTION
**Pull request by dishari-github**
[Interested Tech Writer_Dishari.docx](https://github.com/google/season-of-docs/files/8214963/Interested.Tech.Writer_Dishari.docx)

### CODE REVIEW

**Comment by dishari-github** [comment]
[Interested Tech Writer_Dishari.docx](https://github.com/google/season-of-docs/files/8214973/Interested.Tech.Writer_Dishari.docx)

**Comment by dishari-github** [comment]
[Interested Tech Writer_Dishari.docx](https://github.com/google/season-of-docs/files/8214980/Interested.Tech.Writer_Dishari.docx)

**Comment by dishari-github** [comment]
[Interested Tech Writer_Dishari.docx](https://github.com/google/season-of-docs/files/8215285/Interested.Tech.Writer_Dishari.docx)

**Comment by emckean** [comment]
Closed because information added in PR #452

**Pull request closed without merging**
