### PR TITLE
YASH.md

### PR DESCRIPTION
**Pull request by yashpal2104**
Hey I want to participate in GSOD learn and grow with the company

### CODE REVIEW

**Comment by emckean** [comment]
Hi! Thanks for your interest in Google Season of Docs! Please revise your information to follow our template (Name | Links | Description).

**Comment by yashpal2104** [comment]
Hey I have updated my pull request according to the given template please merge it

**Review by yashpal2104 — COMMENTED** [review]
Reviewed the message corresponds to the template

**Comment by emckean** [comment]
Hi! Thanks for your patience. Could you please ensure your file has the .md extension? Otherwise it will not get added properly. Thanks!

**Comment by yashpal2104** [comment]
hey i have added the .md extension

**Comment by emckean** [comment]
Hi, it looks as if you only changed the title of your PR. Please change the name of your file. Thank you!

**Comment by yashpal2104** [comment]
> Hi, it looks as if you only changed the title of your PR. Please change the name of your file. Thank you!

Hi I am actually new to GitHub can you please  tell me how do I do it

**Comment by yashpal2104** [comment]
Did I do it? I am sorry if I am being annoying

**Comment by yashpal2104** [comment]
Can you merge it now I updated my file @emckean

**Pull request merged**
