### PR TITLE
Adding my details

### PR DESCRIPTION
**Pull request by Tes-program**
Adding my details to interested-technical-writers.md

### CODE REVIEW

**Comment by Tes-program** [comment]
Please i have signed the cla and added my name but it keeps failing @JJ

**Comment by emckean** [comment]
Please check the troubleshooting instructions here: https://github.com/google/season-of-docs/pull/961/checks?check_run_id=11820731629

**Comment by Tes-program** [comment]
@emckean 
Well, I did check and signed the form but here is the issue. Anytime I fill the form with my Github username with the first letter as a capital letter. Then I decided to view my details and it turned them into small letters. I don't know if this is the reason I cant sign the CLA but please tell me what else I can do. Thank you
Screenshot from 2023-03-07 22-18-30

**Comment by emckean** [comment]
It looks like the CL is showing two different accounts, one opening the PR and one as the author. I would advise closing this PR and opening a new one.

**Pull request closed without merging**
